server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test2db'
    username: 'sa'
    password: 'password'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect




